// Automatically generated by astro-icon
// 3798d62078e71522174f7ffeb5b5b4d96c4f264b4fe03954c95d320a2a4d597e

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow"
		| "arrow-next-orange"
		| "arrow-next-white"
		| "arrow-prev-orange"
		| "arrow-prev-white"
		| "arrow-white"
		| "asterisk"
		| "company/babylons"
		| "company/birthday-research"
		| "company/bitcoin"
		| "company/bitmex"
		| "company/defichan"
		| "company/diag"
		| "company/european-commission"
		| "company/gotyme-bank"
		| "company/liquid"
		| "dfa"
		| "dfad"
		| "minus"
		| "plus"
		| "red-dot"
		| "ux-design"
		| "uxdesign";
}