// Automatically generated by astro-icon
// 38101f6ad8d2093f14be933ac1418e418678039d8439f28b836d4ae0b80ca79a

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow"
		| "arrow-next-orange"
		| "arrow-next-white"
		| "arrow-prev-orange"
		| "arrow-prev-white"
		| "arrow-white"
		| "asterisk"
		| "close"
		| "company/babylons"
		| "company/birthday-research"
		| "company/bitcoin"
		| "company/bitmex"
		| "company/defichan"
		| "company/diag"
		| "company/european-commission"
		| "company/gotyme-bank"
		| "company/liquid"
		| "dfa"
		| "dfad"
		| "plus"
		| "red-dot"
		| "ux-design"
		| "uxdesign";
}