// Automatically generated by astro-icon
// fa718bc978273e23b28c8d213b8076f06a4f5bdf7fdf059495d7900ebe722671

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow"
		| "arrow-next-orange"
		| "arrow-next-white"
		| "arrow-prev-orange"
		| "arrow-prev-white"
		| "arrow-white"
		| "asterisk"
		| "company/babylons"
		| "company/birthday-research"
		| "company/bitcoin"
		| "company/bitmex"
		| "company/defichan"
		| "company/diag"
		| "company/european-commission"
		| "company/gotyme-bank"
		| "company/liquid"
		| "dfa"
		| "dfad"
		| "plus"
		| "red-dot"
		| "ux-design"
		| "uxdesign";
}